#!/bin/bash

ASSIGNMENT_NAME=$(echo "$WORKFLOW_INPUTS_JSON" | jq -r '.assignmentName')
ASSIGNMENT_ACCEPT_KEY=$(echo "$WORKFLOW_INPUTS_JSON" | jq -r '.assignmentAcceptKey')

# TODO verify required inputs are present

# Convert app private keys to PKCS8 format, just in case webcrypto
# doesn't play well with PKCS1 again in the future
echo "$ASSIGNMENT_CREATION_APP_PRIVATE_KEY" > private-key-pkcs1.pem
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private-key-pkcs1.pem -out assignment-creation-app-private-key.pem
IFS= read -r -d '' ASSIGNMENT_CREATION_APP_PRIVATE_KEY < assignment-creation-app-private-key.pem || true
export ASSIGNMENT_CREATION_APP_PRIVATE_KEY
rm -f private-key-pkcs1.pem
rm -f assignment-creation-app-private-key.pem

echo "$CLASSROOMS_APP_PRIVATE_KEY" > private-key-pkcs1.pem
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private-key-pkcs1.pem -out classrooms-app-private-key.pem
IFS= read -r -d '' CLASSROOMS_APP_PRIVATE_KEY < classrooms-app-private-key.pem || true
export CLASSROOMS_APP_PRIVATE_KEY
rm -f private-key-pkcs1.pem
rm -f classrooms-app-private-key.pem

echo "$REPO_ACCESS_TOKEN_APP_PRIVATE_KEY" > private-key-pkcs1.pem
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private-key-pkcs1.pem -out repo-access-token-app-private-key.pem
IFS= read -r -d '' REPO_ACCESS_TOKEN_APP_PRIVATE_KEY < repo-access-token-app-private-key.pem || true
export REPO_ACCESS_TOKEN_APP_PRIVATE_KEY
rm -f private-key-pkcs1.pem
rm -f repo-access-token-app-private-key.pem

# Mask assignment accept key in logs
echo "::add-mask::${ASSIGNMENT_ACCEPT_KEY}"

# Git config
git config --global user.name "Classroom Robot"
git config --global user.email "<>"

# Get user's GitHub username and construct student assignment repo
# name
get_user_status=$(curl -s -o curl.json -w "%{http_code}" -L \
    -H "Authorization: Bearer ${USER_ACCESS_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2026-03-10" \
    https://api.github.com/user)

if [[ "$get_user_status" == "401" ]]
then
    echo "Error: Failed authentication when retrieving user information" >&2
    echo -n '{"status": "bad-auth"}' > result/status.json
    exit 0
elif [[ "$get_user_status" != "200" ]]
then
    echo "Error: Got HTTP status $get_user_status when retrieving user information" >&2
    exit 1
fi

export STUDENT_USERNAME=$(cat curl.json | jq -r '.login')
AUTHENTICATED_STUDENT_ID=$(cat curl.json | jq -r '.id')
rm -f curl.json
STUDENT_ASSIGNMENT_REPO="${ASSIGNMENT_NAME}-${STUDENT_USERNAME}"
# Replace forbidden characters with hyphens
export STUDENT_ASSIGNMENT_REPO=$(echo -n "$STUDENT_ASSIGNMENT_REPO" | sed 's/[^a-zA-Z0-9_\.-]/-/g')

# If installation access tokens weren't pulled from cache / were expired, get
# new ones and cache them
if [[ "$assignment_creation_app_installation_access_token" == "" ]]
then
    assignment_creation_app_installation_access_token=$(node repo/workflow-util/getassignmentcreationappinstallationaccesstoken.js)
    # Expire from cache 5 minutes early to avoid mid-workflow expiration
    expiration=$(date -d "+ 55 minutes" --iso-8601=seconds)
    node repo/workflow-util/encodeiatcache.js -t "$assignment_creation_app_installation_access_token" -e "$expiration" -f "cached-app-access-tokens/assignment-creation-app-installation-access-token.json"
else
    echo "Assignment creation app IAT pulled from cache"
fi
echo "::add-mask::${assignment_creation_app_installation_access_token}"

if [[ "$classrooms_app_installation_access_token" == "" ]]
then
    classrooms_app_installation_access_token=$(node repo/workflow-util/getclassroomsappinstallationaccesstoken.js)
    # Expire from cache 5 minutes early to avoid mid-workflow expiration
    expiration=$(date -d "+ 55 minutes" --iso-8601=seconds)
    node repo/workflow-util/encodeiatcache.js -t "$classrooms_app_installation_access_token" -e "$expiration" -f "cached-app-access-tokens/classrooms-app-installation-access-token.json"
else
    echo "Classrooms app IAT pulled from cache"
fi
echo "::add-mask::${classrooms_app_installation_access_token}"

# Clone classrooms repo
git clone --depth 1 "https://${CLASSROOMS_USERNAME}:${classrooms_app_installation_access_token}@${CLASSROOMS_REPO}" classrooms-repo

# Verify that the assignment to be accepted exists (either as a
# directory with contents or in config file)
assignment_exists=1
assignment_template_exists=1
if [[ ! -d "classrooms-repo/assignments/${ASSIGNMENT_NAME}" ]]
then
    assignment_template_exists=0
    if [[ ! -f "classrooms-repo/assignments/assignments.conf" ]]
    then
        assignment_exists=0
    else
        n_matching_assignments=$(cat "classrooms-repo/assignments/assignments.conf" | yq -o json '.[] | select(.name == "'"$ASSIGNMENT_NAME"'")' | jq -s 'length')
        if [[ "$n_matching_assignments" == 0 ]]
        then
            assignment_exists=0
        fi
    fi
fi

if [[ "$assignment_exists" == 0 ]]
then
    # Assignment doesn't exist. Return error to client.
    echo "Error: Assignment \"$ASSIGNMENT_NAME\" doesn't exist" >&2
    echo -n '{"status": "unknown-assignment"}' > result/status.json
    exit 0
fi

# Get classroom's configured timezone UTC offset, sections that this
# student is assigned to, and repo access token permissions
timezone_utc_offset="+00:00"
student_assigned_sections="[]"
if [[ -f "classrooms-repo/classroom.conf" ]]
then
    has_field=$(cat "classrooms-repo/classroom.conf" | yq -o json '.' | jq -j '.timezone_utc_offset != null')
    if [[ "$has_field" == "true" ]]
    then
        timezone_utc_offset=$(cat "classrooms-repo/classroom.conf" | yq -o json | jq -j '.timezone_utc_offset')
    fi

    student_assigned_sections=$(cat "classrooms-repo/classroom.conf" | yq -o json | jq 'if (.roster != null) then .roster else [] end | .[] | select((.github_username | ascii_downcase) == ("'"$STUDENT_USERNAME"'" | ascii_downcase))' | jq -s 'if (length > 0) then .[0] else {} end | if (.sections != null) then .sections else [] end')
    all_section_data=$(cat "classrooms-repo/classroom.conf" | yq -o json | jq 'if (.sections != null) then .sections else [] end')
    repo_access_token_permissions_json=$(cat "classrooms-repo/classroom.conf" | yq -o json | jq -j 'if (.repo_access_token_permissions != null) then .repo_access_token_permissions else "" end')
fi

# Read assignment config as JSON string
overridden_sections="[{}]" # One pseudo section override, does not affect global config when merged in
n_overridden_sections=1
student_override="{}"
if [[ -f "classrooms-repo/assignments/assignments.conf" ]]
then
    assignment_config=$(cat "classrooms-repo/assignments/assignments.conf" | yq -o json '.[] | select(.name == "'"$ASSIGNMENT_NAME"'")' | jq -js 'if (length > 0) then .[0] else "" end')

    if [[ "$assignment_config" != "" ]]
    then
        all_section_overrides=$(echo "$assignment_config" | jq 'if (.section_overrides != null) then .section_overrides else [] end')
        n_student_assigned_sections=$(echo "$student_assigned_sections" | jq -j 'length')
        cur_overridden_sections=""
        for i in $(seq "$n_student_assigned_sections")
        do
            idx=$((i-1))
            student_assigned_section=$(echo "$student_assigned_sections" | jq '.['"$idx"']')
            cur_overridden_section=$(echo "$all_section_overrides" | jq '.[] | select(.section == '"$student_assigned_section"')' | jq -s 'if (length > 0) then .[0] else {} end')
            cur_overridden_sections+="$cur_overridden_section"
        done
        
        if [[ "$n_student_assigned_sections" -gt 0 ]]
        then
            overridden_sections=$(echo "$cur_overridden_sections" | jq -s)
            n_overridden_sections=$(echo "$overridden_sections" | jq -j 'length') # Should match n_student_assigned_sections
        fi
    
        student_override=$(echo "$assignment_config" | jq 'if (.student_overrides != null) then .student_overrides else [] end | .[] | select((.github_username | ascii_downcase) == ("'"$STUDENT_USERNAME"'" | ascii_downcase))' | jq -s 'if (length > 0) then .[0] else {} end')
    fi
fi

# Function to merge config JSON fields into shell variables
function merge_in_config_json() {
    has_field=$(echo "$1" | jq -j '.key != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_accept_key=$(echo "$1" | jq -j '.key')
    fi

    has_field=$(echo "$1" | jq -j '.student_role != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_student_role=$(echo "$1" | jq -j '.student_role')
    fi

    has_field=$(echo "$1" | jq -j '.release_at != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_release_at=$(echo "$1" | jq -j '.release_at')
    fi

    has_field=$(echo "$1" | jq -j '.unrelease_at != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_unrelease_at=$(echo "$1" | jq -j '.unrelease_at')
    fi

    has_field=$(echo "$1" | jq -j '.release_at_section_start != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_release_at_section_start=$(echo "$1" | jq -j '.release_at_section_start')
    fi

    has_field=$(echo "$1" | jq -j '.unrelease_at_section_end != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_unrelease_at_section_end=$(echo "$1" | jq -j '.unrelease_at_section_end')
    fi

    has_field=$(echo "$1" | jq -j '.accept_generates_invite != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_accept_generates_invite=$(echo "$1" | jq -j '.accept_generates_invite')
    fi

    has_field=$(echo "$1" | jq -j '.accept_generates_repo_access_token != null')
    if [[ "$has_field" == "true" ]]
    then
        assignment_accept_generates_repo_access_token=$(echo "$1" | jq -j '.accept_generates_repo_access_token')
    fi
}

# Record success in finding valid config under which assignment
# can be accepted
found_matching_config=0

# For each per-section config override for sections this student is assigned to:
for i in $(seq "$n_overridden_sections")
do
    idx=$((i-1))

    # Reset config values to default
    assignment_accept_key=""
    assignment_student_role="push"
    assignment_release_at=""
    assignment_unrelease_at=""
    assignment_release_at_section_start="false"
    assignment_unrelease_at_section_end="false"
    assignment_accept_generates_invite="true"
    assignment_accept_generates_repo_access_token="false"

    # If assignment config is present, merge in top-level config
    if [[ "$assignment_config" != "" ]]
    then
        merge_in_config_json "$assignment_config"
    fi

    # Merge in per-section config override (for sections without overrides in
    # assignment config, or if the student isn't assigned to any sections, the
    # override object will be an empty object, so merging will have no effect
    # on the existing config shell variables)
    overridden_section=$(echo "$overridden_sections" | jq '.['"$idx"']')
    merge_in_config_json "$overridden_section"
    
    # Merge in per-student config override, if present (if absent,
    # $student_override will be an empty object, so merging will have no effect
    # on the existing config shell variables)
    merge_in_config_json "$student_override"
    
    # All overrides merged. Config is prepared.

    # Check if input key doesn't match assignment's configured accept key.
    if [[ "$assignment_accept_key" != "" && "$assignment_accept_key" != "$ASSIGNMENT_ACCEPT_KEY" ]]
    then
        # Invalid accept key. Continue to next per-section
        # config override
        continue
    fi

    # Compute start of release window
    release_at_iso_8601=""
    if [[ "$assignment_release_at" != "" ]]
    then
        release_at_iso_8601="${assignment_release_at}${timezone_utc_offset}"
    fi

    if [[ "$assignment_release_at_section_start" == "true" ]]
    then
        # Must shift release_at forward to section's next start time. Get
        # section name from $overridden_section.
        section_name=$(echo "$overridden_section" | jq -j 'if (.section != null) then .section else "" end')
        if [[ "$section_name" == "" ]]
        then
            # Exception: no section name. Must be pseudo section (student is not
            # assigned to any sections, but assignment is configured to be
            # released at start of assigned section). Then release start can't
            # be computed, so assignment never releases for student. Continue
            # to next assigned section (though there should be no more)
            continue
        fi

        # Section has name. Not a pseudosection.
        section_data=$(echo "$all_section_data" | jq '.[] | select(.name == "'"$section_name"'")' | jq -s 'if (length > 0) then .[0] else {} end')
        
        # Get section weekday and start time
        section_weekday=$(echo "$section_data" | jq -j 'if (.weekday != null) then .weekday else "" end')
        section_start_time=$(echo "$section_data" | jq -j 'if (.start_time != null) then .start_time else "" end')
        
        # Shift release_at_iso_8601 forward to section weekday and start time.
        release_at_day=$(echo "$assignment_release_at" | cut -d 'T' -f 1)
        release_at_time=$(echo "$assignment_release_at" | cut -d 'T' -f 2)
        release_at_weekday_number=$(date -d "$release_at_day" +%u)
        section_weekday_number=$(date -d "next ${section_weekday}" +%u)
        if [[ "$release_at_weekday_number" != "$section_weekday_number" ]]
        then
            # Release-at weekday is different from section weekday. Shift
            # forward to next instance of section weekday, then set time to
            # section start time
            shift_amount=$(((section_weekday_number + 7 - release_at_weekday_number) % 7))
            shifted_release_at_day=$(date -d "${release_at_day} + ${shift_amount} days" +%Y-%m-%d)
            release_at_iso_8601="${shifted_release_at_day}T${section_start_time}${timezone_utc_offset}"
        else
            # Release-at weekday is same as section weekday. Check if
            # release-at time is before or at section start time.
            release_at_seconds_since_epoch=$(date -d "$release_at_time" +%s)
            section_start_time_seconds_since_epoch=$(date -d "$section_start_time" +%s)
            if [[ "$release_at_seconds_since_epoch" -le "$section_start_time_seconds_since_epoch" ]]
            then
                # Releases earlier in day than section start time. Shift
                # forward to section start time
                release_at_iso_8601="${release_at_day}T${section_start_time}${timezone_utc_offset}"
            else
                # Releases later in day than section start time. Shift
                # forward by one week and to section start time.
                shifted_release_at_day=$(date -d "${release_at_day} + 1 week" +%Y-%m-%d)
                release_at_iso_8601="${shifted_release_at_day}T${section_start_time}${timezone_utc_offset}"
            fi
        fi
    fi

    # Compute end of release window similarly
    unrelease_at_iso_8601=""
    if [[ "$assignment_unrelease_at" != "" ]]
    then
        unrelease_at_iso_8601="${assignment_unrelease_at}${timezone_utc_offset}"
    fi

    if [[ "$assignment_unrelease_at_section_end" == "true" ]]
    then
        # Must shift unrelease_at forward to section's next end time. Get
        # section name from $overridden_section.
        section_name=$(echo "$overridden_section" | jq -j 'if (.section != null) then .section else "" end')
        if [[ "$section_name" == "" ]]
        then
            # No section name. Pseudosection. No unrelease time. Never
            # unrelease for this student.
            unrelease_at_iso_8601=""
        else
            # Section name present. Not a pseudosection. Assignment unreleases
            # for student at section end time.
            section_data=$(echo "$all_section_data" | jq '.[] | select(.name == "'"$section_name"'")' | jq -s 'if (length > 0) then .[0] else {} end')
            
            # Get section weekday and end time
            section_weekday=$(echo "$section_data" | jq -j 'if (.weekday != null) then .weekday else "" end')
            section_end_time=$(echo "$section_data" | jq -j 'if (.end_time != null) then .end_time else "" end')
            
            # Shift unrelease_at_iso_8601 forward to section weekday and end time.
            unrelease_at_day=$(echo "$assignment_unrelease_at" | cut -d 'T' -f 1)
            unrelease_at_time=$(echo "$assignment_unrelease_at" | cut -d 'T' -f 2)
            unrelease_at_weekday_number=$(date -d "$unrelease_at_day" +%u)
            section_weekday_number=$(date -d "next ${section_weekday}" +%u)
            if [[ "$unrelease_at_weekday_number" != "$section_weekday_number" ]]
            then
                # Unrelease-at weekday is different from section weekday. Shift
                # forward to next instance of section weekday, then set time to
                # section end time
                shift_amount=$(((section_weekday_number + 7 - unrelease_at_weekday_number) % 7))
                shifted_unrelease_at_day=$(date -d "${unrelease_at_day} + ${shift_amount} days" +%Y-%m-%d)
                unrelease_at_iso_8601="${shifted_unrelease_at_day}T${section_end_time}${timezone_utc_offset}"
            else
                # Unrelease-at weekday is same as section weekday. Check if
                # unrelease-at time is before or at section end time.
                unrelease_at_seconds_since_epoch=$(date -d "$unrelease_at_time" +%s)
                section_end_time_seconds_since_epoch=$(date -d "$section_end_time" +%s)
                if [[ "$unrelease_at_seconds_since_epoch" -le "$section_end_time_seconds_since_epoch" ]]
                then
                    # Unreleases earlier in day than section end time. Shift
                    # forward to section end time
                    unrelease_at_iso_8601="${unrelease_at_day}T${section_end_time}${timezone_utc_offset}"
                else
                    # Unreleases later in day than section end time. Shift
                    # forward by one week and to section end time.
                    shifted_unrelease_at_day=$(date -d "${unrelease_at_day} + 1 week" +%Y-%m-%d)
                    unrelease_at_iso_8601="${shifted_unrelease_at_day}T${section_end_time}${timezone_utc_offset}"
                fi
            fi
        fi
    fi

    # Check if we're outside release window.
    now_seconds_since_epoch=$(date +%s)
    if [[ "$release_at_iso_8601" != "" ]]
    then
        # Release window has start. Check if we're before start.
        release_at_seconds_since_epoch=$(date -d "$release_at_iso_8601" +%s)
        if [[ "$now_seconds_since_epoch" -lt "$release_at_seconds_since_epoch" ]]
        then
            # Currently before release window start. Not yet released. Continue
            # to next assigned section.
            continue
        fi
    fi

    if [[ "$unrelease_at_iso_8601" != "" ]]
    then
        # Release window has end. Check if we're after end.
        unrelease_at_seconds_since_epoch=$(date -d "$unrelease_at_iso_8601" +%s)
        if [[ "$now_seconds_since_epoch" -ge "$unrelease_at_seconds_since_epoch" ]]
        then
            # Currently at or after release window end. Unreleased. Continue
            # to next assigned section.
            continue
        fi
    fi

    # Inside release window. Assignment can be accepted under this section's
    # configuration. Report success and stop iterating through assigned
    # sections.
    found_matching_config=1
    break
done

# If unsuccessful in finding configuration that allows assignment acceptance,
# report error and terminate
if [[ "$found_matching_config" == "0" ]]
then
    echo "Error: Failed to accept assignment\"$ASSIGNMENT_NAME\". Perhaps accept key \"$ASSIGNMENT_ACCEPT_KEY\" is invalid, or we're outside release window(s)." >&2
    echo -n '{"status": "denied"}' > result/status.json
    exit 0
fi

# Assignment can be accepted.

# Check if student assignment repo already exists.
get_remote_repo_status=$(curl -s -o /dev/null -w "%{http_code}" -L \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${assignment_creation_app_installation_access_token}" \
    -H "X-GitHub-Api-Version: 2026-03-10" \
    "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}")

if [[ "$get_remote_repo_status" == "404" ]]
then
    # Repo doesn't exist. Create it.
    create_remote_repo_status=$(curl -s -o /dev/null -w "%{http_code}" -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${assignment_creation_app_installation_access_token}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        "https://api.github.com/orgs/${STUDENT_ASSIGNMENT_ORGANIZATION}/repos" \
        -d '{"name":"'"$STUDENT_ASSIGNMENT_REPO"'","description":"'"${STUDENT_USERNAME}'s"' repository for assignment '"$ASSIGNMENT_NAME"'","private":true}')

    if [[ "$create_remote_repo_status" == "403" ]]
    then
        echo "Error: Authentication failed when generating student assignment repository" >&2
        exit 1
    elif [[ "$create_remote_repo_status" == "422" ]]
    then
        echo "Error: Got HTTP status 422 when generating assignment repository." >&2
        exit 1
    elif [[ "$create_remote_repo_status" != "201" ]]
    then
        echo "Error: Got HTTP status $create_remote_repo_status when generating student assignment repository" >&2
        exit 1
    fi

    # If assignment template directory exists, then create local
    # student assignment repo and push contents to remote
    # repo
    if [[ "$assignment_template_exists" == 1 ]]
    then
        mkdir -p "$STUDENT_ASSIGNMENT_REPO"
        cp -a classrooms-repo/assignments/"$ASSIGNMENT_NAME"/. "$STUDENT_ASSIGNMENT_REPO"
        (
            cd "$STUDENT_ASSIGNMENT_REPO"
            git init -b main
            git add -A
            git commit -m "Classroom Robot: Instantiate assignment"
            remote_repo_git_url="https://${ASSIGNMENT_CREATION_USERNAME}:${assignment_creation_app_installation_access_token}@${STUDENT_PLATFORM_GIT_HOSTNAME}/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}.git"
            git push "$remote_repo_git_url" main
        )
    fi
elif [[ "$get_remote_repo_status" != "200" ]]
then
    # HTTP 200 means repo exists. 404 means it doesn't. Anything else
    # is an error.
    echo "Error: Got HTTP status $get_remote_repo_status when retrieving student assignment repository" >&2
    exit 1
fi

if [[ "$assignment_accept_generates_invite" == "true" ]]
then
    # Accept generates invite.
    # Check if student already has access to repository.
    get_collaborator_status=$(curl -s -o /dev/null -w "%{http_code}" -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${USER_ACCESS_TOKEN}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}/collaborators/$STUDENT_USERNAME")
    if [[ "$get_collaborator_status" == "404" ]]
    then
        # User is not a collaborator. Record that we may need to add them.
        student_needs_invite=1
    elif [[ "$get_collaborator_status" != "204" ]]
    then
        # HTTP 204 means already a collaborator, 404 means not a
        # collaborator. Anything else is an error.
        echo "Error: Got HTTP status $get_collaborator_status when checking if student is a collaborator on their assignment repository" >&2
        exit 1
    fi

fi

if [[ "$assignment_accept_generates_repo_access_token" == "true" ]]
then
    # Accept generates repo access token. Record that it needs to be
    # generated (these tokens are per-student-repo and are cached strictly by
    # the frontend, so they're regenerated on every request)
    student_needs_repo_access_token=1
fi

# If student needs any form of assignment access, before we can grant it to
# them, we first have to check if this repo was previously created and
# registered under a different student's ID. Get STUDENT_ID repository variable
# if it exists
if [[ "$student_needs_invite" == 1 || "$student_needs_repo_access_token" == 1 ]]
then
    get_student_id_status=$(curl -s -o curl.json -w "%{http_code}" -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${assignment_creation_app_installation_access_token}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}/actions/variables/STUDENT_ID")
    if [[ "$get_student_id_status" == 200 ]]
    then
        # Extract variable value from curl.json
        STUDENT_ID=$(cat curl.json | jq -r '.value')
    else
        # Variable doesn't exist. Then the repo can be registered to this
        # student. Create
        # the STUDENT_ID variable using ID of current authenticated
        # user.
        STUDENT_ID="$AUTHENTICATED_STUDENT_ID"
        create_student_id_status=$(curl -s -o /dev/null -w "%{http_code}" -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${assignment_creation_app_installation_access_token}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}/actions/variables" \
            -d '{"name":"STUDENT_ID","value":"'"$AUTHENTICATED_STUDENT_ID"'"}')
        if [[ "$create_student_id_status" != 201 ]]
        then
            # Failed to create repo variable.
            echo "Error: Got HTTP status $create_student_id_status when creating STUDENT_ID repository variable" >&2
            exit 1
        fi
    fi
        
    # Verify that current authenticated user's ID matches that of student
    # registered for repository
    if [[ "$STUDENT_ID" != "$AUTHENTICATED_STUDENT_ID" ]]
    then
        # Wrong student. Should only happen if students' GitHub usernames
        # change, so two students have the same username throughout the
        # duration of a classroom's use. This repo was previously registered
        # to a different student with this username.
        # Fail with duplicate-username. Requires instructor to intervene
        # and rename the old duplicate repository to something else.
        echo "Error: Failed authentication when retrieving user information" >&2
        echo -n '{"status": "duplicate-username"}' > result/status.json
        exit 0
    fi
fi

# If we made it this far, all checks have passed. Student can be granted
# access to repo if necessary.

if [[ "$student_needs_invite" == 1 ]]
then
    # Send invite to add student as outside collaborator for repo, or add
    # as collaborator directly under certain conditions (e.g., if they're
    # a member of the organization, or a member of a team that's already
    # a collaborator)
    add_collaborator_status=$(curl -L \
        -s -o /dev/null -w "%{http_code}" \
        -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${assignment_creation_app_installation_access_token}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}/collaborators/${STUDENT_USERNAME}" \
        -d '{"permission":"'"$assignment_student_role"'"}')

    if [[ "$add_collaborator_status" == "403" ]]
    then
        echo "Error: Authentication failed when adding student as collaborator to their assignment repository" >&2
        exit 1
    elif [[ "$add_collaborator_status" != "204" && "$add_collaborator_status" != 201 ]]
    then
        # HTTP 204 (no content) means student was added directly
        # as collaborator (no invite was needed), or they were
        # already a collaborator. HTTP 201 means an invite was
        # sent. Anything else is an error.
        echo "Error: Got HTTP status $add_collaborator_status when adding student as collaborator to their assignment repository" >&2
        exit 1
    fi
fi

if [[ "$student_needs_repo_access_token" == 1 ]]
then
    if [[ "$repo_access_token_permissions_json" != "" ]]
    then
        repo_access_token=$(node repo/workflow-util/getrepoaccesstoken.js -r "$STUDENT_ASSIGNMENT_REPO" -p "$repo_access_token_permissions_json")
    else
        repo_access_token=$(node repo/workflow-util/getrepoaccesstoken.js -r "$STUDENT_ASSIGNMENT_REPO")
    fi
fi

# Store result
student_repository_url="https://${STUDENT_PLATFORM_GIT_HOSTNAME}/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}"
echo -n '{' > result/data.json
if [[ "$assignment_accept_generates_invite" == "true" ]]
then
    if [[ "$needs_commas" == 1 ]]
    then
        echo -n ',' >> result/data.json
    fi
    needs_commas=1
    echo -n '"repositoryURL": "'"$student_repository_url"'"' >> result/data.json
fi
if [[ "$repo_access_token" != "" ]]
then
    if [[ "$needs_commas" == 1 ]]
    then
        echo -n ',' >> result/data.json
    fi
    needs_commas=1
    echo -n '"repositoryAccessToken": "'"$repo_access_token"'"' >> result/data.json
    echo -n ',"repositoryRemoteURL": "'"https://${ASSIGNMENT_CREATION_USERNAME}:${repo_access_token}@${STUDENT_PLATFORM_GIT_HOSTNAME}/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}.git"'"' >> result/data.json
fi
echo -n '}' >> result/data.json
echo -n '{"status": "success"}' > result/status.json
exit 0
